version: 1
formatters:
  simple:
    format: '[%(asctime)s][%(name)s][%(levelname)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  iqotion_api:
    level: INFO
    handlers: [console]
    propagate: no
  iqoption_api.call:
    level: ERROR
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: []